### ISSUE TITLE
Is this lexer not compatible with Npp v8.4 64bit?

### ISSUE THREAD

**Issue by danergo** [Ekopalypse/NppPythonScripts#10] opened 2022-05-05 19:00 UTC
Is it possible that this lexer (https://github.com/Ekopalypse/NppPythonScripts/blob/master/npp/error_list_lexer_support.py) became incompatible with the latest NPP?

I used it last week, but now I have updated NPP, and doesn't seem to do anything, it leaves the ESC sequences intact.

Thank you very much if you could confirm this in either direction :)

**Comment by Ekopalypse** [comment] 2022-05-05 20:30
Yes, I think you are right. Npp has moved towards the ILexer5 interface which no longer supports SCI_SETLEXER, instead it now uses SCI_SETILEXER which itself requires a pointer to the ILexer5 instance.
I'm not sure if the problem can be solved without Npp supporting this as well. I'll have to think about it.

**Comment by Ekopalypse** [comment] 2022-05-06 12:16
@danergo - I've uploaded a second version of the errorlist lexer which should be compatible with ILexer5

![image](https://user-images.githubusercontent.com/47723516/167129579-c818c7fe-e1b9-4fb0-82e2-c9e5a56fda07.png)

**Comment by danergo** [comment] 2022-05-06 12:24
@Ekopalypse: hi, 

For me it's not happening, no coloring, but also no error messages in the console:

![image](https://user-images.githubusercontent.com/11708344/167130538-6c7764eb-feb4-43eb-a92e-5ab5b155bd6f.png)

What I see mine is a *bit* newer build (Apr 20 vs Apr 15), and my *Local Conf mode" is OFF.

**Comment by Ekopalypse** [comment] 2022-05-06 12:29
... and you use PythonScript 2 where I use PythonScript 3.
I will download and test it.

**Comment by danergo** [comment] 2022-05-06 12:36
Ah yes. How can I switch to PS3? It seems it's not available via *Plugins Admin*:

![image](https://user-images.githubusercontent.com/11708344/167132411-b2864e25-ba4c-4afc-a3da-2d83be5ad961.png)

![image](https://user-images.githubusercontent.com/11708344/167132458-d6edca7b-5669-4f54-8be4-4ddcbabef995.png)

**Comment by Ekopalypse** [comment] 2022-05-06 12:36
Yes, I can reproduce the issue with PythonScript2.

PythonScript3 is not "officially" available due to an unsolved issue with ANSI encoded data. It is only available through [github releases page](https://github.com/bruderstein/PythonScript/releases)

But gimme a few minutes, I think I should be able to make it work with PS2 as well.

**Comment by Ekopalypse** [comment] 2022-05-06 13:07
I suppose I have fixed the problem. PS2 uses byte strings, while PS3 uses Unicode strings by default.

![image](https://user-images.githubusercontent.com/47723516/167137264-e3b111c4-e48a-4d8c-830b-1daeced94d2d.png)

**Comment by danergo** [comment] 2022-05-06 13:22
Yes, it works!

However, on a large logfile (5M lines), it is not coloring it. If I copy lines (100, 1000, 10000) it works. I'm trying to find out what is the max size constraint for this to work :)

Strange, copying all lines to a new file and it still works.

If I open a large logfile, coloring will not work. However, if I do CTRL+A, CTRL+C, new file, CTRL+V, save with txt or log extension, it will be colored (all 5M lines) :)

**Comment by Ekopalypse** [comment] 2022-05-06 13:29
If I remember correctly, there has been another change in Npp in this regard recently, involving support for large files, but must admit that I have not done any testing myself.
I suppose I will find some time tomorrow to do some tests in this regard.

**Comment by danergo** [comment] 2022-05-06 13:31
Sure, thank you so much! I can help you with testing, as I have this large logfile by hand :)

**Comment by Ekopalypse** [comment] 2022-05-06 13:33
> If I open a large logfile, coloring will not work. However, if I do CTRL+A, CTRL+C, new file, CTRL+V, save with txt or log extension, it will be colored (all 5M lines) :)

Could you check if the coloring occurs when you move to the last position of the file?

**Comment by danergo** [comment] 2022-05-06 13:59
No, it doesn't. Only way currently to make it work for a large file is the method I posted above.

**Comment by Ekopalypse** [comment] 2022-05-09 10:25
@danergo - the problem seems to be related to [this](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/9cc01de97c8d2a617c7ada7aba6854a9f7e1426b/PowerEditor/src/ScintillaComponent/Buffer.h#L27). What is [checked](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/48ee390cdd922e271cd4e3906a262c0f9fd21e51/PowerEditor/src/ScintillaComponent/Buffer.cpp#L689) when [loading a file](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/48ee390cdd922e271cd4e3906a262c0f9fd21e51/PowerEditor/src/ScintillaComponent/Buffer.cpp#L673).
I'm thinking about how to work around this problem, at the cost, of course, of dramatically slowing down the loading of large error list files.
Double checked with a large xml and json file - neither are coloured.

**Comment by Ekopalypse** [comment] 2022-05-14 07:46
@danergo 
In the Scintilla api there seems to be no way to change this afterwards. The only reasonable option I can see is that Npp supports some kind of flag that allows the user to override the default option that documents larger than 200 MB are colored. Sorry I can't be more helpful. I've opened an [issue](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/11670) to address this.

**Comment by Ekopalypse** [comment] 2022-11-02 19:56
Tested with Notepad++ v8.4.7 (64-bit) RC, which introduces a switch to configure the file limit size.
If this is included in the final version, from my point of view this issue can be closed.

![image](https://user-images.githubusercontent.com/47723516/199589357-d56a28f8-3d64-49a5-9add-4f14ebac55f4.png)

**Comment by danergo** [comment] 2022-11-03 07:43
Perfect, @Ekopalypse: I think you can close this now, thank you very much for not giving this up. :) I appreciate your efforts!

**Comment by Ekopalypse** [comment] 2022-11-08 16:20
Closing as announced, as the changes have been incorporated into the final version 8.4.7.

**Closed as completed by Ekopalypse** 2022-11-08 16:20 UTC
Labels: Notepad++ related
